# Generated by Django 4.2.13 on 2026-09-21 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_membersubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('SENT_TO_SNIPPE', 'Sent to Snippe'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=14),
        ),
    ]
