# Generated by Django 4.2.13 on 2026-08-29 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_auto_verify_existing_members'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_label', models.CharField(max_length=80)),
                ('declared_at', models.DateField()),
                ('status', models.CharField(choices=[('DECLARED', 'Declared'), ('PAID', 'Paid')], default='DECLARED', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='declared_share_outs', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_outs', to='groups.vikobagroup')),
            ],
            options={
                'ordering': ['-declared_at'],
                'unique_together': {('group', 'cycle_label')},
            },
        ),
        migrations.CreateModel(
            name='MemberShareOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_out_entries', to='members.member')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_share_outs', to=settings.AUTH_USER_MODEL)),
                ('share_out', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='groups.shareout')),
            ],
            options={
                'ordering': ['-id'],
                'unique_together': {('share_out', 'member')},
            },
        ),
    ]
