# Generated by Django 4.2.13 on 2026-08-29 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_alter_member_user'),
        ('groups', '0002_shareout_membershareout'),
    ]

    operations = [
        migrations.AddField(
            model_name='vikobagroup',
            name='country',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='vikobagroup',
            name='region',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.CreateModel(
            name='GroupRoleVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('TREASURER', 'Treasurer'), ('SECRETARY', 'Secretary')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_role_votes_received', to='members.member')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_votes', to='groups.vikobagroup')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_role_votes_cast', to='members.member')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupRoleCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('TREASURER', 'Treasurer'), ('SECRETARY', 'Secretary')], max_length=20)),
                ('declared_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_candidates', to='groups.vikobagroup')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_role_candidacies', to='members.member')),
            ],
            options={
                'ordering': ['declared_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='grouprolevote',
            constraint=models.UniqueConstraint(fields=('group', 'role', 'voter'), name='unique_group_role_voter'),
        ),
        migrations.AddConstraint(
            model_name='grouprolecandidate',
            constraint=models.UniqueConstraint(fields=('group', 'member', 'role'), name='unique_group_candidate_role'),
        ),
    ]
