"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 4.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""


import os
from pathlib import Path
from datetime import timedelta
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
try:
    from dotenv import load_dotenv
except Exception:  # pragma: no cover - deployment resilience
    load_dotenv = None

# Load .env for local/dev only when python-dotenv is available.
if load_dotenv is not None:
    load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
_SECRET_KEY_ENV = os.environ.get("DJANGO_SECRET_KEY")
SECRET_KEY = _SECRET_KEY_ENV or "django-insecure-local-development-fallback"

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG=True
# Honour the common "False"/"0"/"off" string values instead of treating any
# non-empty string as truthy (bool("False") is True in Python).
DEBUG = os.environ.get("DEBUG", "0").lower() in ("1", "true", "yes", "on")

if not _SECRET_KEY_ENV and not DEBUG:
    from django.core.exceptions import ImproperlyConfigured

    raise ImproperlyConfigured(
        "DJANGO_SECRET_KEY must be set via the environment when DEBUG is disabled."
    )

# Domains that are allowed to serve this Django application.
# Read an explicit, comma-separated list from the environment (DJANGO_ALLOWED_HOSTS)
# and always permit local dev plus any *.onrender.com preview/production domain.
_allowed_hosts_env = os.environ.get("DJANGO_ALLOWED_HOSTS", "")
ALLOWED_HOSTS = [h.strip() for h in _allowed_hosts_env.split(",") if h.strip()]
ALLOWED_HOSTS += ["localhost", "127.0.0.1", "[::1]", ".onrender.com"]
if DEBUG:
    ALLOWED_HOSTS.append("*")

# Security hardening. Headers that are safe in every environment.
X_FRAME_OPTIONS = "DENY"
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True
SECURE_REFERRER_POLICY = "same-origin"

# TLS-related settings are only meaningful when running behind HTTPS. Render
# terminates TLS at the edge, so anything above the proxy is plain HTTP.
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # my apps
    'users.apps.UsersConfig',
    'customers.apps.CustomersConfig',
    'members.apps.MembersConfig',
    "accounts.apps.AccountsConfig",
    "loans.apps.LoansConfig",
    "groups.apps.GroupsConfig",
    "community.apps.CommunityConfig",
    "whatsapp.apps.WhatsappConfig",
    "payments.apps.PaymentsConfig",
    "finance.apps.FinanceConfig",
    "governance.apps.GovernanceConfig",

    # Third party apps
    'rest_framework',
    "corsheaders",
    'rest_framework_simplejwt',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
#
# Local Python development should work without a running database service, so it
# defaults to SQLite. Docker Compose sets DATABASE_MODE=postgres explicitly.
# Set DATABASE_MODE=postgres locally only when you deliberately want to connect
# to a locally running PostgreSQL instance.
#
# On Render a PostgreSQL instance is attached and its connection string is
# injected as DATABASE_URL, which takes precedence over the discrete variables.
DATABASE_MODE = os.getenv("DATABASE_MODE", "sqlite").lower()

DATABASE_URL = os.getenv("DATABASE_URL")

if DATABASE_URL:
    import dj_database_url

    DATABASES = {
        "default": dj_database_url.parse(DATABASE_URL, conn_max_age=600),
    }
elif DATABASE_MODE == "sqlite":
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / os.getenv("SQLITE_DATABASE_NAME", "db.sqlite3"),
        }
    }
elif DATABASE_MODE in {"postgres", "postgresql"}:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.getenv("DATABASE_NAME", "vikoba-kidigitali-db"),
            "USER": os.getenv("DATABASE_USERNAME", "admin"),
            "PASSWORD": os.getenv("DATABASE_PASSWORD", "password"),
            "HOST": os.getenv("DATABASE_HOST", "127.0.0.1"),
            "PORT": os.getenv("DATABASE_PORT", "5432"),
        }
    }
else:
    raise ValueError("DATABASE_MODE must be either 'sqlite' or 'postgres'.")

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
# WhiteNoise serves and compresses static files directly in production.
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Render terminates TLS at the edge and forwards the original protocol.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
# media file configurations
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field


# Platform branding used in emails
SYSTEM_NAME = os.environ.get("SYSTEM_NAME", "Vikoba Kidigitali")

# Email delivery - Gmail SMTP is enabled when credentials are provided (Render).
# In local development without credentials we use the console backend so nothing
# is actually sent and codes behave like the phone OTP dev mode. Host, port and
# TLS are environment-overridable so another provider can be plugged in without
# code changes (e.g. EMAIL_HOST=smtp.zoho.com EMAIL_PORT=465 EMAIL_USE_SSL=true).
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD")

if EMAIL_HOST_USER and EMAIL_HOST_PASSWORD:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = os.environ.get("EMAIL_HOST", "smtp.gmail.com")
    EMAIL_PORT = int(os.environ.get("EMAIL_PORT", "587"))
    EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS", "true").lower() in (  # 587
        "1", "true", "yes", "on",
    )
    EMAIL_USE_SSL = os.environ.get("EMAIL_USE_SSL", "false").lower() in (  # 465
        "1", "true", "yes", "on",
    )
    EMAIL_TIMEOUT = int(os.environ.get("EMAIL_TIMEOUT", "30"))
else:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

DEFAULT_FROM_EMAIL = EMAIL_HOST_USER or "noreply@vikobakidigitali.app"

# Announce the active mail backend at startup so a missing/misconfigured SMTP
# is obvious in the deployment logs instead of silently swallowing emails.
if EMAIL_BACKEND.endswith("smtp.EmailBackend"):
    import logging as _mail_logging

    _mail_logging.getLogger(__name__).warning(
        "EMAIL: SMTP backend -> %s:%s (tls=%s ssl=%s, from=%s)",
        EMAIL_HOST,
        EMAIL_PORT,
        EMAIL_USE_TLS,
        EMAIL_USE_SSL,
        DEFAULT_FROM_EMAIL,
    )
else:
    import logging as _mail_logging

    _mail_logging.getLogger(__name__).warning(
        "EMAIL: CONSOLE backend (no EMAIL_HOST_USER/EMAIL_HOST_PASSWORD) - "
        "no real emails will be sent until SMTP credentials are configured."
    )

# The API is public at its Render host but only trusted by one frontend origin.
# Production accepts requests from the Vercel app only; localhost is added only
# while running with DEBUG enabled so local development keeps working.
PRODUCTION_FRONTEND_ORIGIN = "https://vikoba-theta.vercel.app"

DEFAULT_CORS_ALLOWED_ORIGINS = [PRODUCTION_FRONTEND_ORIGIN]

# Allow extra origins via the environment (e.g. a custom frontend domain) without
# editing code. Values are comma-separated.
_extra_cors = os.environ.get("CORS_ALLOWED_ORIGINS", "")
EXTRA_CORS_ORIGINS = [o.strip() for o in _extra_cors.split(",") if o.strip()]

if DEBUG:
    DEFAULT_CORS_ALLOWED_ORIGINS += [
        "http://localhost:5173",
        "http://127.0.0.1:5173",
        "http://localhost:3000",
        "http://127.0.0.1:3000",
    ]

CORS_ALLOWED_ORIGINS = DEFAULT_CORS_ALLOWED_ORIGINS + EXTRA_CORS_ORIGINS

# The API authenticates with bearer tokens (stored in localStorage), not
# cookies, so credentialed requests are never needed.
CORS_ALLOW_CREDENTIALS = False

# Required for unsafe methods (POST/PUT/PATCH/DELETE) when CSRF checks are in play.
CSRF_TRUSTED_ORIGINS = [
    PRODUCTION_FRONTEND_ORIGIN,
] + EXTRA_CORS_ORIGINS

# No wildcard/preview origins: the backend listens for exactly one frontend.
CORS_ALLOWED_ORIGIN_REGEXES = []

REST_FRAMEWORK = {
    'COERCE_DECIMAL_TO_STRING': False,
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    # Deny by default. Endpoints must explicitly opt in (e.g. AllowAny on the
    # public auth endpoints) instead of relying on a permissive default.
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    # Throttle anonymous traffic (e.g. password reset) and scope-sensitive
    # auth endpoints (login, registration, password reset) via throttle_scope.
    'DEFAULT_THROTTLE_CLASSES': (
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.ScopedRateThrottle',
    ),
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/min',
        'auth': '30/min',
        'pin': '10/min',
    },
}

# Simple JWT
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": False,
    "UPDATE_LAST_LOGIN": False,

    "ALGORITHM": "HS256",
    "SIGNING_KEY": os.environ.get("JWT_SIGNING_KEY") or SECRET_KEY,
    "VERIFYING_KEY": "",
    "AUDIENCE": None,
    "ISSUER": None,
    "JSON_ENCODER": None,
    "JWK_URL": None,
    "LEEWAY": 0,

    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "USER_AUTHENTICATION_RULE": "rest_framework_simplejwt.authentication.default_user_authentication_rule",

    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
    "TOKEN_USER_CLASS": "rest_framework_simplejwt.models.TokenUser",

    "JTI_CLAIM": "jti",

    "SLIDING_TOKEN_REFRESH_EXP_CLAIM": "refresh_exp",
    "SLIDING_TOKEN_LIFETIME": timedelta(minutes=5),
    "SLIDING_TOKEN_REFRESH_LIFETIME": timedelta(days=1),

    "TOKEN_OBTAIN_SERIALIZER": "rest_framework_simplejwt.serializers.TokenObtainPairSerializer",
    "TOKEN_REFRESH_SERIALIZER": "rest_framework_simplejwt.serializers.TokenRefreshSerializer",
    "TOKEN_VERIFY_SERIALIZER": "rest_framework_simplejwt.serializers.TokenVerifySerializer",
    "TOKEN_BLACKLIST_SERIALIZER": "rest_framework_simplejwt.serializers.TokenBlacklistSerializer",
    "SLIDING_TOKEN_OBTAIN_SERIALIZER": "rest_framework_simplejwt.serializers.TokenObtainSlidingSerializer",
    "SLIDING_TOKEN_REFRESH_SERIALIZER": "rest_framework_simplejwt.serializers.TokenRefreshSlidingSerializer",
}

# Loan eligibility settings. These are warnings for staff review, never an
# automatic rejection of a loan application.
LOAN_MINIMUM_MEMBERSHIP_MONTHS = int(
    os.getenv("LOAN_MINIMUM_MEMBERSHIP_MONTHS", "3")
)
LOAN_MINIMUM_MONTHLY_CONTRIBUTION = os.getenv(
    "LOAN_MINIMUM_MONTHLY_CONTRIBUTION", "0.00"
)

# Overdue penalty defaults (monthly rate % and grace days). Groups can override
# these through their GroupLoanPolicy.
LOAN_PENALTY_RATE = os.getenv("LOAN_PENALTY_RATE", "0.00")
LOAN_PENALTY_GRACE_DAYS = int(os.getenv("LOAN_PENALTY_GRACE_DAYS", "7"))

# When set, a loan is only auto-classified DEFAULTED after this many days since
# disbursement. Leave unset (None) to keep automatic default classification off.
LOAN_DEFAULT_THRESHOLD_DAYS = os.getenv("LOAN_DEFAULT_THRESHOLD_DAYS")

# ---------------------------------------------------------------------------
# Withdrawal governance (Phase 4).
#
# Per-group overrides live in GroupWithdrawalPolicy (governance app); these
# platform values are inherited when a group leaves a field unset.
#   WITHDRAWAL_AUTO_LIMIT_TZS     - withdrawals up to this amount auto-approve
#                                   and are paid without human review
#                                   (None = unlimited auto-processing)
#   WITHDRAWAL_MAX_LIMIT_TZS      - hard ceiling per withdrawal (None = none)
#   WITHDRAWAL_MIN_AMOUNT_TZS     - minimum single withdrawal (None = none)
#   WITHDRAWAL_MIN_RETAINED_RATIO - fraction of the balance retained after a
#                                   withdrawal (0 = nothing mandated)
# ---------------------------------------------------------------------------
WITHDRAWAL_AUTO_LIMIT_TZS = os.getenv("WITHDRAWAL_AUTO_LIMIT_TZS")
WITHDRAWAL_MAX_LIMIT_TZS = os.getenv("WITHDRAWAL_MAX_LIMIT_TZS")
WITHDRAWAL_MIN_AMOUNT_TZS = os.getenv("WITHDRAWAL_MIN_AMOUNT_TZS")
WITHDRAWAL_MIN_RETAINED_RATIO = os.getenv("WITHDRAWAL_MIN_RETAINED_RATIO", "0")
WITHDRAWAL_POLICY_VERSION = "platform-default-v1"

# Manual review: roles that may act on governance requests (in addition to the
# committee role the group policy requests). Never includes MEMBER.
GOVERNANCE_OFFICER_ROLES = ("AD", "MA", "OP", "FI", "AC")

# How long a manual-review approval stays open before it expires and releases
# the reserved funds.
APPROVAL_EXPIRY_HOURS = int(os.getenv("APPROVAL_EXPIRY_HOURS", "72"))

AUTH_USER_MODEL = "users.User"
# No append slash at the end of URL
# APPEND_SLASH = True

# Phone OTP delivery. Simulated mode returns the code in the API response so the
# demo (and local development) can complete verification without an SMS gateway.
# Flip to "false" only once a real SMS provider is integrated.
OTP_DEV_MODE = os.getenv("OTP_DEV_MODE", "true").lower() in (
    "1", "true", "yes", "on",
)

# Snippe mobile-money gateway (sandbox for local/demo; live creds on Render).
# The API key and webhook secret are secrets — they must never be committed to
# git and are only read from the environment / .env.
SNIPPE_BASE_URL = os.getenv("SNIPPE_BASE_URL", "https://api.snippe.sh").rstrip("/")
SNIPPE_API_KEY = os.getenv("SNIPPE_API_KEY", "")
SNIPPE_WEBHOOK_SECRET = os.getenv("SNIPPE_WEBHOOK_SECRET", "")
SNIPPE_WEBHOOK_URL = os.getenv("SNIPPE_WEBHOOK_URL", "").rstrip("/")
SNIPPE_ENVIRONMENT = os.getenv("SNIPPE_ENVIRONMENT", "sandbox")
# When enabled the provider returns synthetic responses and never dials out; it
# mirrors OTP_DEV_MODE so the demo and tests run with no network/Snippe account.
SNIPPE_DEV_MODE = os.getenv("SNIPPE_DEV_MODE", "true").lower() in (
    "1", "true", "yes", "on",
)
SNIPPE_TIMEOUT = int(os.getenv("SNIPPE_TIMEOUT", "10"))

if not SNIPPE_DEV_MODE and not SNIPPE_API_KEY:
    raise ImproperlyConfigured("SNIPPE_API_KEY must be set when SNIPPE_DEV_MODE is off.")

# When no real SMTP credentials are configured the console mail backend is used;
# returning the code to the caller mirrors phone OTP dev mode for local dev/demo.
EMAIL_DEV_MODE = EMAIL_BACKEND == "django.core.mail.backends.console.EmailBackend"

# Baileys WhatsApp gateway. WHATSAPP_BRIDGE_URL is the base URL of the
# whatsapp-bridge service (e.g. https://my-bridge.onrender.com); the token must
# match BRIDGE_TOKEN on the bridge side. Leave unset to disable WhatsApp
# delivery and fall back to SMS/logged messages.
WHATSAPP_BRIDGE_URL = os.getenv("WHATSAPP_BRIDGE_URL", "").rstrip("/")
WHATSAPP_BRIDGE_TOKEN = os.getenv("WHATSAPP_BRIDGE_TOKEN", "")

# Minimum delay (seconds) a member must wait between phone OTP requests.
OTP_RESEND_COOLDOWN_SECONDS = int(os.getenv("OTP_RESEND_COOLDOWN_SECONDS", "120"))

# Structured logging to the console. DJANGO_LOGLEVEL (default "info") controls
# the root level; django.request warnings surface 4xx/5xx failures on stdout.
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "simple": {
            "format": "{levelname} {asctime} {module}: {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": os.getenv("DJANGO_LOGLEVEL", "info").upper(),
    },
    "loggers": {
        "django.request": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        },
    },
}
