# Generated by Django 4.2.13 on 2026-09-21 08:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0004_groupactivity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('WITHDRAWAL', 'Withdrawal'), ('LOAN_APPLICATION', 'Loan application'), ('DEPOSIT', 'Deposit request'), ('POLICY_CHANGE', 'Group policy change'), ('GROUP_EXPENSE', 'Group expense'), ('FINANCIAL_ADJUSTMENT', 'Financial adjustment')], max_length=30)),
                ('object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('resource_description', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('currency', models.CharField(default='TZS', max_length=4)),
                ('required_level', models.CharField(choices=[('AUTO', 'Automatic'), ('MANUAL', 'Manual review'), ('MULTI', 'Multi-level review')], default='MANUAL', max_length=10)),
                ('required_role', models.CharField(blank=True, help_text='Role required to approve (committee role like TREASURER, or staff role code).', max_length=40)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('AUTO_APPROVED', 'Auto approved'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('decision', models.CharField(blank=True, choices=[('AUTO_APPROVED', 'Auto approved'), ('MANUAL_REVIEW', 'Manual review'), ('REJECTED', 'Rejected')], max_length=20, null=True)),
                ('decision_reason', models.TextField(blank=True)),
                ('rules_passed', models.JSONField(blank=True, default=list)),
                ('policy_version', models.CharField(blank=True, max_length=60)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('idempotency_key', models.CharField(blank=True, help_text='Optional idempotency guard for exactly-once submission.', max_length=120, null=True, unique=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_requests', to='groups.vikobagroup')),
                ('requester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_approval_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupWithdrawalPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_approve_limit', models.DecimalField(blank=True, decimal_places=2, help_text='Withdrawals up to this amount are auto-approved; above it goes to manual review. None = unlimited.', max_digits=14, null=True)),
                ('max_withdrawal_limit', models.DecimalField(blank=True, decimal_places=2, help_text='Hard ceiling per withdrawal. None = no ceiling.', max_digits=14, null=True)),
                ('min_withdrawal_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum single withdrawal. None = no minimum.', max_digits=14, null=True)),
                ('weekly_withdrawal_limit', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum total withdrawn by a member per rolling week before manual review.', max_digits=14, null=True)),
                ('weekly_withdrawal_count', models.PositiveSmallIntegerField(blank=True, help_text='Maximum number of withdrawals a member can make per rolling week before manual review.', null=True)),
                ('monthly_withdrawal_limit', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum total withdrawn by a member per rolling month before manual review.', max_digits=14, null=True)),
                ('min_retained_ratio', models.DecimalField(blank=True, decimal_places=2, help_text='Fraction of the savings balance that must remain after the withdrawal. None = 0.', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('review_on_outstanding_loan', models.BooleanField(default=False, help_text='Route to manual review when the member has an outstanding loan.')),
                ('review_on_outstanding_penalty', models.BooleanField(default=False, help_text='Route to manual review when the member has an unpaid loan penalty.')),
                ('review_levels', models.CharField(choices=[('SINGLE', 'Single review'), ('TWO_LEVEL', 'Treasurer + Chairperson')], default='SINGLE', help_text='Review levels required for a manual-review withdrawal.', max_length=12)),
                ('reviewer_role', models.CharField(choices=[('CHAIRPERSON', 'Chairperson'), ('SECRETARY', 'Secretary'), ('TREASURER', 'Treasurer')], default='TREASURER', help_text='Committee role required for manual approval.', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_policy', to='groups.vikobagroup')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_withdrawal_policies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(default=1)),
                ('role', models.CharField(max_length=40)),
                ('required_human', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=12)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_approval_steps', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='governance.approvalrequest')),
            ],
            options={
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_type', models.CharField(choices=[('SYSTEM', 'System'), ('HUMAN', 'Human')], default='HUMAN', max_length=10)),
                ('action', models.CharField(max_length=30)),
                ('decision', models.CharField(blank=True, choices=[('AUTO_APPROVED', 'Auto approved'), ('MANUAL_REVIEW', 'Manual review'), ('REJECTED', 'Rejected')], max_length=20, null=True)),
                ('reason', models.TextField(blank=True)),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(blank=True, max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='governance_actions', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='governance.approvalrequest')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='approvalstep',
            constraint=models.UniqueConstraint(fields=('request', 'level'), name='unique_approval_step_level'),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['status', 'request_type'], name='governance__status_262f33_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['content_type', 'object_id'], name='governance__content_73c775_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalaction',
            index=models.Index(fields=['request', 'created_at'], name='governance__request_a9ba15_idx'),
        ),
    ]
