# Generated by Django 4.2.13 on 2026-09-23 06:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import kyc.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0008_member_phone_network'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KYCProfile',
            fields=[
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='kyc_profile', serialize=False, to='members.member')),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not started'), ('PENDING', 'Verification pending'), ('IN_REVIEW', 'In review'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired'), ('REQUIRES_UPDATE', 'Requires update'), ('PROVIDER_ERROR', 'Provider error')], db_index=True, default='NOT_STARTED', help_text='Current KYC state (NOT a frontend-controllable field — only the backend verification process or an authorised reviewer transitions it).', max_length=20)),
                ('verification_level', models.CharField(choices=[('LEVEL_0', 'Unverified'), ('LEVEL_1', 'Basic verification'), ('LEVEL_2', 'Full verification')], default='LEVEL_0', max_length=10)),
                ('verification_method', models.CharField(choices=[('NONE', 'None'), ('MANUAL_REVIEW', 'Manual review'), ('PROVIDER', 'Verification provider'), ('BOTH', 'Manual review + provider')], default='NONE', max_length=20)),
                ('provider', models.CharField(blank=True, default='', max_length=40)),
                ('provider_reference', models.CharField(blank=True, default='', max_length=120)),
                ('failure_code', models.CharField(blank=True, default='', max_length=40)),
                ('failure_reason', models.CharField(blank=True, default='', max_length=255)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When the current verification stops being valid.', null=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='KYCVerificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_ref', models.CharField(default=kyc.models.new_request_ref, max_length=20, unique=True)),
                ('idempotency_key', models.CharField(blank=True, help_text='Client-supplied key; repeating a submission with the same key never creates a second provider request.', max_length=120, null=True, unique=True)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('PROCESSING', 'Processing'), ('SUCCESS', 'Success'), ('REJECTED', 'Rejected'), ('PROVIDER_ERROR', 'Provider error'), ('EXPIRED', 'Expired')], db_index=True, default='SUBMITTED', max_length=20)),
                ('attempt_count', models.PositiveSmallIntegerField(default=1)),
                ('max_attempts', models.PositiveSmallIntegerField(default=3)),
                ('provider', models.CharField(blank=True, default='', max_length=40)),
                ('provider_reference', models.CharField(blank=True, help_text='Provider-side reference for this attempt (masked in responses).', max_length=120, null=True, unique=True)),
                ('verification_status', models.CharField(blank=True, default='', max_length=20)),
                ('failure_code', models.CharField(blank=True, default='', max_length=40)),
                ('failure_reason', models.CharField(blank=True, default='', max_length=255)),
                ('match_result', models.JSONField(blank=True, default=dict, help_text='Match flags only, e.g. {"full_name": true, "date_of_birth": true, "national_id": true}. Never raw identity values.')),
                ('verified_name', models.CharField(blank=True, default='', max_length=255)),
                ('verified_dob', models.DateField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='kyc.kycprofile')),
            ],
            options={
                'ordering': ['-submitted_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='KYCEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=40)),
                ('status', models.CharField(blank=True, default='', max_length=20)),
                ('from_status', models.CharField(blank=True, default='', max_length=20)),
                ('to_status', models.CharField(blank=True, default='', max_length=20)),
                ('provider', models.CharField(blank=True, default='', max_length=40)),
                ('provider_reference', models.CharField(blank=True, default='', max_length=120)),
                ('failure_code', models.CharField(blank=True, default='', max_length=40)),
                ('actor_type', models.CharField(choices=[('SYSTEM', 'System'), ('HUMAN', 'Human')], default='SYSTEM', max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_events', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='kyc.kycprofile')),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='kyc.kycverificationrequest')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='kycverificationrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['SUBMITTED', 'PROCESSING'])), fields=('profile',), name='kyc_request_single_active'),
        ),
        migrations.AddIndex(
            model_name='kycevent',
            index=models.Index(fields=['profile', 'created_at'], name='kyc_kyceven_profile_d28917_idx'),
        ),
    ]
