# Generated by Django 4.2.13 on 2026-08-29 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0003_vikobagroup_country_vikobagroup_region_grouprolevote_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=64, unique=True)),
                ('owner_type', models.CharField(choices=[('ADMIN', 'System admin'), ('CHAIR', 'Group chairperson')], max_length=8)),
                ('display_name', models.CharField(blank=True, default='', max_length=120)),
                ('status', models.CharField(choices=[('connecting', 'Connecting'), ('scanning', 'Scanning QR'), ('connected', 'Connected'), ('disconnected', 'Disconnected'), ('logged_out', 'Logged out'), ('error', 'Error')], default='connecting', max_length=20)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('is_primary', models.BooleanField(default=False, help_text="Preferred sender for that owner scope (e.g. the admin's main device).")),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_sessions_created', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_sessions', to='groups.vikobagroup')),
            ],
            options={
                'ordering': ['-is_primary', '-updated_at'],
                'indexes': [models.Index(fields=['owner_type', 'status'], name='whatsapp_wh_owner_t_973bbf_idx')],
            },
        ),
    ]
