# Generated by Django 4.2.13 on 2026-08-29 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappsession',
            name='status',
            field=models.CharField(choices=[('connecting', 'Connecting'), ('awaiting_pairing', 'Awaiting pairing code'), ('connected', 'Connected'), ('disconnected', 'Disconnected'), ('logged_out', 'Logged out'), ('error', 'Error')], default='connecting', max_length=20),
        ),
    ]
