# Generated by Django 4.2.13 on 2026-08-29 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('whatsapp', '0002_alter_whatsappsession_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappsession',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User account the device is saved to (the chairperson or the staff member).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_owned', to=settings.AUTH_USER_MODEL),
        ),
    ]
