# Generated by Django 4.2.13 on 2026-09-20 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loans', '0005_loanschedule_repayment_audit'),
        ('members', '0008_member_phone_network'),
        ('accounts', '0005_membersubscription'),
        ('groups', '0004_groupactivity'),
        ('payments', '0003_paymenttransaction_subscription_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=60)),
                ('reference', models.CharField(blank=True, db_index=True, max_length=60)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FinancialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(db_index=True, editable=False, max_length=40, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('account_type', models.CharField(choices=[('ASSET', 'Asset'), ('LIABILITY', 'Liability'), ('EQUITY', 'Equity'), ('INCOME', 'Income'), ('EXPENSE', 'Expense')], max_length=10)),
                ('currency', models.CharField(default='TZS', max_length=3)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CLOSED', 'Closed')], db_index=True, default='ACTIVE', max_length=10)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['account_number'],
            },
        ),
        migrations.CreateModel(
            name='FinancialTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(db_index=True, editable=False, max_length=60, unique=True)),
                ('transaction_type', models.CharField(choices=[('CONTRIBUTION', 'Contribution'), ('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('LOAN_DISBURSEMENT', 'Loan disbursement'), ('LOAN_REPAYMENT', 'Loan repayment'), ('INTEREST', 'Interest'), ('PENALTY', 'Penalty'), ('REFUND', 'Refund'), ('TRANSFER', 'Transfer'), ('GROUP_EXPENSE', 'Group expense'), ('MEMBERSHIP_FEE', 'Membership fee'), ('PLATFORM_FEE', 'Platform fee'), ('SUBSCRIPTION', 'Subscription'), ('ADJUSTMENT', 'Adjustment'), ('REVERSAL', 'Reversal')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('currency', models.CharField(default='TZS', max_length=3)),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('REVERSED', 'Reversed'), ('REFUNDED', 'Refunded'), ('RECONCILIATION_REQUIRED', 'Needs reconciliation')], db_index=True, default='INITIATED', max_length=30)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('external_reference', models.CharField(blank=True, max_length=120)),
                ('provider', models.CharField(blank=True, max_length=30)),
                ('provider_transaction_id', models.CharField(blank=True, db_index=True, help_text='Provider-side reference (only set when we uniquely know it).', max_length=120, null=True, unique=True)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, help_text='Guarantees a repeated request can never create a second transaction.', max_length=64, null=True, unique=True)),
                ('reversal_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], max_length=6)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('currency', models.CharField(default='TZS', max_length=3)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='ReferenceCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=8)),
                ('day', models.CharField(help_text='YYYYMMDD', max_length=8)),
                ('last_sequence', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddConstraint(
            model_name='referencecounter',
            constraint=models.UniqueConstraint(fields=('prefix', 'day'), name='unique_reference_counter_prefix_day'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries', to='finance.financialaccount'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='finance.financialtransaction'),
        ),
        migrations.AddField(
            model_name='financialtransaction',
            name='contribution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_transactions', to='groups.groupcontribution'),
        ),
        migrations.AddField(
            model_name='financialtransaction',
            name='deposit_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_transactions', to='accounts.depositrequest'),
        ),
        migrations.AddField(
            model_name='financialtransaction',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_transactions', to='groups.vikobagroup'),
        ),
        migrations.AddField(
            model_name='financialtransaction',
            name='initiated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_financial_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='financialtransaction',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financial_transactions', to='members.member'),
        ),
        migrations.AddField(
            model_name='financialtransaction',
            name='payment_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_transactions', to='payments.paymenttransaction'),
        ),
        migrations.AddField(
            model_name='financialtransaction',
            name='reversal_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversals', to='finance.financialtransaction'),
        ),
        migrations.AddField(
            model_name='financialtransaction',
            name='savings_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_transactions', to='accounts.savingstransaction'),
        ),
        migrations.AddField(
            model_name='financialtransaction',
            name='withdrawal_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_transactions', to='accounts.withdrawalrequest'),
        ),
        migrations.AddField(
            model_name='financialaccount',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_accounts', to='groups.vikobagroup'),
        ),
        migrations.AddField(
            model_name='financialaccount',
            name='loan_account',
            field=models.OneToOneField(blank=True, help_text='Linked operational loan account for receivable accounts.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_account', to='loans.loanaccount'),
        ),
        migrations.AddField(
            model_name='financialaccount',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_accounts', to='members.member'),
        ),
        migrations.AddField(
            model_name='financialaccount',
            name='savings_account',
            field=models.OneToOneField(blank=True, help_text='Linked operational savings account for member-scoped accounts.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_account', to='accounts.savingsaccount'),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='finance.financialtransaction'),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_audit_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', 0)), name='journal_entry_positive_amount'),
        ),
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.UniqueConstraint(fields=('transaction', 'position'), name='unique_journal_entry_position'),
        ),
    ]
