# Generated by Django 4.2.13 on 2026-09-20 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_seed_chart_of_accounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialtransaction',
            name='transaction_type',
            field=models.CharField(choices=[('CONTRIBUTION', 'Contribution'), ('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('LOAN_DISBURSEMENT', 'Loan disbursement'), ('LOAN_REPAYMENT', 'Loan repayment'), ('INTEREST', 'Interest'), ('PENALTY', 'Penalty'), ('REFUND', 'Refund'), ('TRANSFER', 'Transfer'), ('GROUP_EXPENSE', 'Group expense'), ('MEMBERSHIP_FEE', 'Membership fee'), ('PLATFORM_FEE', 'Platform fee'), ('PROVIDER_FEE', 'Provider fee'), ('SUBSCRIPTION', 'Subscription'), ('ADJUSTMENT', 'Adjustment'), ('REVERSAL', 'Reversal')], max_length=30),
        ),
    ]
