# Generated by Django 4.2.13 on 2026-09-20 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0005_loanschedule_repayment_audit'),
        ('finance', '0003_alter_financialtransaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialtransaction',
            name='loan',
            field=models.ForeignKey(blank=True, help_text='Loan this journal belongs to (loan-specific journals only).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_transactions', to='loans.loanaccount'),
        ),
    ]
