from django.urls import path

from . import views

app_name = "groups"

urlpatterns = [
    path('groups', views.GroupListView.as_view(), name='group-list'),
    path('groups/invitations/pending',
         views.GroupPendingInvitationsView.as_view(),
         name='group-pending-invitations'),
    path('groups/me/summary',
         views.GroupDashboardSummaryView.as_view(),
         name='group-dashboard-summary'),
    path('groups/me/share-outs',
         views.MemberShareOutListView.as_view(),
         name='my-share-outs'),
    path('groups/share-outs',
         views.ShareOutListView.as_view(),
         name='share-out-list'),
    path('groups/share-outs/create',
         views.ShareOutCreateView.as_view(),
         name='share-out-create'),
    path('groups/share-outs/<int:share_out_id>/pay/<str:membership_number>',
         views.ShareOutPayView.as_view(),
         name='share-out-pay'),
    path('groups/<int:group_id>', views.GroupDetailView.as_view(), name='group-detail'),
    path('groups/<int:group_id>/overview',
         views.GroupWorkspaceOverviewView.as_view(), name='group-overview'),
    path('groups/<int:group_id>/members',
         views.GroupMembersView.as_view(), name='group-members'),
    path('groups/<int:group_id>/loans',
         views.GroupLoansView.as_view(), name='group-loans'),
    path('groups/<int:group_id>/repayments',
         views.GroupRepaymentsView.as_view(), name='group-repayments'),
    path('groups/<int:group_id>/ledger',
         views.GroupLedgerView.as_view(), name='group-ledger'),
    path('groups/<int:group_id>/activity',
         views.GroupActivityListView.as_view(), name='group-activity'),
    path('groups/<int:group_id>/invite',
         views.GroupInviteView.as_view(), name='group-invite'),
    path('groups/<int:group_id>/join',
         views.GroupJoinView.as_view(), name='group-join'),
    path('groups/accept-invite',
         views.GroupAcceptInviteView.as_view(), name='group-accept-invite'),
    path('groups/<int:group_id>/shares',
         views.GroupSharesView.as_view(), name='group-shares'),
    path('groups/<int:group_id>/committee',
         views.GroupCommitteeView.as_view(), name='group-committee'),
    path('groups/<int:group_id>/committee/declare',
         views.GroupCommitteeDeclareView.as_view(), name='group-committee-declare'),
    path('groups/<int:group_id>/committee/vote',
         views.GroupCommitteeVoteView.as_view(), name='group-committee-vote'),
    path('groups/<int:group_id>/committee/close',
         views.GroupCommitteeCloseView.as_view(), name='group-committee-close'),
    path('groups/<int:group_id>/contributions',
         views.GroupContributionsView.as_view(), name='group-contributions'),
    path('groups/<int:group_id>/contributions/<int:contribution_id>/confirm',
         views.GroupContributionDecisionView.as_view(),
         name='group-contribution-decision'),
]
