# Generated by Django 4.2.13 on 2026-09-18 09:52

from django.db import migrations, models
import django.db.models.deletion
import payments.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0003_vikobagroup_country_vikobagroup_region_grouprolevote_and_more'),
        ('accounts', '0004_alter_withdrawalrequest_status'),
        ('members', '0007_member_citizenship_type_member_gender_and_more'),
        ('loans', '0005_loanschedule_repayment_audit'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('event_type', models.CharField(db_index=True, max_length=40)),
                ('api_version', models.CharField(blank=True, max_length=20)),
                ('payload', models.JSONField(default=dict)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_reference', models.CharField(db_index=True, default=payments.models._internal_reference, editable=False, help_text='Our reference (VCB-TX-...); the idempotency anchor for a retry.', max_length=40, unique=True)),
                ('transaction_type', models.CharField(choices=[('CONTRIBUTION', 'Group contribution'), ('LOAN_REPAYMENT', 'Loan repayment'), ('LOAN_DISBURSEMENT', 'Loan disbursement'), ('WITHDRAWAL', 'Withdrawal'), ('OTHER', 'Other')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('currency', models.CharField(default='TZS', max_length=3)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=20)),
                ('provider', models.CharField(default='snippe', max_length=20)),
                ('provider_reference', models.CharField(blank=True, db_index=True, help_text='Reference given to us by Snippe for the payment/payout.', max_length=100, null=True, unique=True)),
                ('external_reference', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled'), ('VOIDED', 'Voided')], db_index=True, default='PENDING', max_length=12)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('idempotency_key', models.CharField(db_index=True, editable=False, max_length=30, unique=True)),
                ('installment_number', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('contribution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transactions', to='groups.groupcontribution')),
                ('deposit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transactions', to='accounts.depositrequest')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transactions', to='groups.vikobagroup')),
                ('loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transactions', to='loans.loanaccount')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_transactions', to='members.member')),
                ('withdrawal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transactions', to='accounts.withdrawalrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
