# Generated by Django 4.2.13 on 2026-09-19 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_membersubscription'),
        ('payments', '0002_alter_paymenttransaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transactions', to='accounts.membersubscription'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='transaction_type',
            field=models.CharField(choices=[('CONTRIBUTION', 'Group contribution'), ('LOAN_REPAYMENT', 'Loan repayment'), ('LOAN_DISBURSEMENT', 'Loan disbursement'), ('WITHDRAWAL', 'Withdrawal'), ('DEPOSIT', 'Wallet deposit'), ('SUBSCRIPTION', 'Plan subscription'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
