# Generated by Django 4.2.13 on 2026-09-20 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0003_paymenttransaction_subscription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled'), ('VOIDED', 'Voided'), ('RECONCILIATION_REQUIRED', 'Needs reconciliation')], db_index=True, default='PENDING', max_length=30),
        ),
        migrations.CreateModel(
            name='ReconciliationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='snippe', max_length=20)),
                ('provider_reference', models.CharField(blank=True, db_index=True, max_length=100)),
                ('internal_reference', models.CharField(blank=True, db_index=True, max_length=40)),
                ('event_id', models.CharField(blank=True, max_length=100)),
                ('issue_type', models.CharField(choices=[('AMOUNT_MISMATCH', 'Amount discrepancy'), ('CURRENCY_MISMATCH', 'Currency mismatch'), ('UNKNOWN_PROVIDER_TRANSACTION', 'Unknown provider transaction'), ('DUPLICATE_PROVIDER_TRANSACTION', 'Duplicate provider transaction'), ('MISSING_INTERNAL_TRANSACTION', 'Missing internal transaction'), ('MISSING_WEBHOOK', 'Missing webhook'), ('DELAYED_CONFIRMATION', 'Delayed confirmation'), ('STATUS_MISMATCH', 'Status mismatch'), ('ALREADY_PROCESSED_EVENT', 'Already processed event'), ('PROVIDER_ERROR', 'Provider error')], db_index=True, max_length=40)),
                ('expected_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('actual_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('expected_currency', models.CharField(blank=True, max_length=3)),
                ('actual_currency', models.CharField(blank=True, max_length=3)),
                ('expected_status', models.CharField(blank=True, max_length=30)),
                ('actual_status', models.CharField(blank=True, max_length=30)),
                ('resolution_status', models.CharField(choices=[('OPEN', 'Open'), ('RESOLVED', 'Resolved')], db_index=True, default='OPEN', max_length=12)),
                ('notes', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(blank=True, help_text='Null when the provider transaction has no internal payment yet.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliation_records', to='payments.paymenttransaction')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciled_payment_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='reconciliationrecord',
            constraint=models.UniqueConstraint(fields=('provider', 'provider_reference', 'issue_type'), name='unique_reconciliation_provider_ref_issue'),
        ),
    ]
