# Generated by Django 4.2.13 on 2026-08-28 14:53

from django.db import migrations


def auto_verify_existing_members(apps, schema_editor):
    """Staff-created members are trusted and start fully verified."""
    Member = apps.get_model("members", "Member")
    Member.objects.filter(registration_source="ADMIN").update(is_verified=True)


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_member_is_verified_member_phone_verified_and_more'),
    ]

    operations = [
        migrations.RunPython(auto_verify_existing_members, migrations.RunPython.noop),
    ]
