# Generated by Django 4.2.13 on 2026-09-17 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_membershipplan'),
        ('members', '0006_alter_member_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='citizenship_type',
            field=models.CharField(blank=True, choices=[('BY_BIRTH', 'By birth'), ('NATURALIZATION', 'By naturalization / application'), ('MARRIAGE', 'By marriage')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='is_onboarded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='onboarded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='permanent_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='member',
            name='preferred_currency',
            field=models.CharField(choices=[('TZS', 'TZS'), ('USD', 'USD')], default='TZS', max_length=3),
        ),
        migrations.AddField(
            model_name='member',
            name='region',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='member',
            name='selected_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='accounts.membershipplan'),
        ),
        migrations.AddField(
            model_name='member',
            name='street',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='member',
            name='country',
            field=models.CharField(blank=True, default='Tanzania', max_length=100),
        ),
    ]
