# Generated by Django 4.2.13 on 2026-09-19 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_member_citizenship_type_member_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='phone_network',
            field=models.CharField(blank=True, choices=[('mpesa', 'M-Pesa'), ('airtel', 'Airtel Money'), ('mixx', 'Mixx by Yas'), ('halotel', 'Halotel'), ('unknown', 'Unknown')], default='unknown', max_length=10),
        ),
    ]
