# Generated by Django 4.2.13 on 2026-09-20 18:14

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0004_groupactivity'),
        ('loans', '0005_loanschedule_repayment_audit'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanaccount',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanaccount',
            name='interest_type',
            field=models.CharField(choices=[('reducing', 'Reducing Balance'), ('flat', 'Flat Rate')], default='reducing', max_length=20),
        ),
        migrations.AddField(
            model_name='loanaccount',
            name='outstanding_penalty',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Accumulated penalty charges not yet paid.', max_digits=12),
        ),
        migrations.AddField(
            model_name='loanaccount',
            name='penalty_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monthly penalty rate (%) applied to overdue installments.', max_digits=5),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='approved_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Final amount approved at the approval step. May differ from the requested amount.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancelled_loan_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Group this application belongs to. Inferred at submission and used for group lending policy.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_applications', to='groups.vikobagroup'),
        ),
        migrations.AddField(
            model_name='loanschedule',
            name='partially_paid_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cumulative amount already paid toward this installment without settling it.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('disbursed', 'Disbursed')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='LoanPenalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('PAID', 'Paid'), ('WAIVED', 'Waived')], default='OPEN', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('waived_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('installment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='penalties', to='loans.loanschedule')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='penalties', to='loans.loanaccount')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GroupLoanPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('max_term_months', models.PositiveIntegerField(blank=True, null=True)),
                ('multiplier', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('interest_type', models.CharField(blank=True, choices=[('reducing', 'Reducing Balance'), ('flat', 'Flat Rate')], max_length=20, null=True)),
                ('requires_guarantors', models.BooleanField(blank=True, null=True)),
                ('penalty_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Monthly penalty rate (%) applied to overdue installments.', max_digits=5, null=True)),
                ('penalty_grace_days', models.PositiveIntegerField(blank=True, help_text='Days past due before a penalty is applied.', null=True)),
                ('group_capacity_enabled', models.BooleanField(default=True, help_text='Limit total group lending against aggregate member savings.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loan_policy', to='groups.vikobagroup')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_loan_policies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='loanpenalty',
            constraint=models.UniqueConstraint(condition=models.Q(('installment__isnull', False)), fields=('loan', 'installment'), name='unique_loan_installment_penalty'),
        ),
    ]
