# Generated by Django 4.2.13 on 2026-09-20 18:16

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0006_loan_and_penalty_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanpenalty',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cumulative payment allocated to this penalty.', max_digits=12),
        ),
    ]
