# Generated by Django 4.2.13 on 2026-09-23 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0007_loanpenalty_amount_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouploanpolicy',
            name='kyc_level_required',
            field=models.CharField(blank=True, choices=[('LEVEL_0', 'LEVEL_0'), ('LEVEL_1', 'LEVEL_1'), ('LEVEL_2', 'LEVEL_2')], help_text='KYC verification level the member must satisfy before a loan is approved/disbursed. None = inherit the platform KYC_REQUIRED_LEVEL default.', max_length=10, null=True),
        ),
    ]
